services:
  valkey-7000:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7000
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7000.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7000:/data

  valkey-7001:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7001
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7001.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7001:/data

  valkey-7002:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7002
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7002.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7002:/data

  valkey-7003:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7003
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7003.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7003:/data

  valkey-7004:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7004
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7004.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7004:/data

  valkey-7005:
    image: ${VALKEY_IMAGE:-valkey/valkey:7.2-alpine}
    container_name: valkey-7005
    network_mode: "host"
    command: ["valkey-server", "/usr/local/etc/valkey/valkey.conf"]
    volumes:
      - ./conf/valkey-7005.conf:/usr/local/etc/valkey/valkey.conf
      - ./data/7005:/data